# Generated by Django 3.1.12 on 2024-12-20 01:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdCard',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attack', models.IntegerField()),
                ('attribute', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('ch_name', models.CharField(max_length=200)),
                ('defence', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('eng_name', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('jp_name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('stars', models.IntegerField()),
            ],
            options={
                'db_table': 'md',
            },
        ),
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ability_effect', models.TextField()),
                ('ability_info', models.CharField(max_length=255)),
                ('attacks', jsonfield.fields.JSONField()),
                ('card_number', models.CharField(max_length=50)),
                ('evolves_link', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('illustrator', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('resistance', models.CharField(max_length=50)),
                ('retreat_cost', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('weakness', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pokemoncards',
            },
        ),
        migrations.CreateModel(
            name='TrainerCard',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('card_ability', models.TextField()),
                ('card_number', models.CharField(max_length=50)),
                ('illustrator', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trainercards',
            },
        ),
    ]
